-- AlterEnum
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'WELCOME';
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'ACCOUNT_CREATED';
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET';
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'PAYMENT_RECEIVED';
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'PAYMENT_CONFIRMED';
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'PAYMENT_REJECTED';
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'TICKET_RECEIVED';
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'ADMIN_NEW_REGISTRATION';
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'ADMIN_PAYMENT_SUBMITTED';
ALTER TYPE "EmailTemplateKey" ADD VALUE IF NOT EXISTS 'ADMIN_NEW_TICKET';
